global using ControlzEx.Theming;
global using MahApps.Metro.Controls;
global using MahApps.Metro.Controls.Dialogs;
global using MahApps.Metro.IconPacks;
global using MoreLinq;
global using Newtonsoft.Json;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Drawing;
global using System.Drawing.Imaging;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Reflection;
global using System.Resources;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Forms;
global using System.Windows.Input;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using YoutubeExplode;
global using YoutubeExplode.Channels;
global using YoutubeExplode.Common;
global using YoutubeExplode.Playlists;
global using YoutubeExplode.Videos;
global using YoutubeExplode.Videos.Streams;
global using YoutubePlaylistDownloader.Objects;
global using YoutubePlaylistDownloader.Utilities;
global using NotifyCollectionChangedAction = System.Collections.Specialized.NotifyCollectionChangedAction;
global using NotifyCollectionChangedEventArgs = System.Collections.Specialized.NotifyCollectionChangedEventArgs;
global using CacheControlHeaderValue = System.Net.Http.Headers.CacheControlHeaderValue;
global using Application = System.Windows.Application;
global using Clipboard = System.Windows.Clipboard;
global using Button = System.Windows.Controls.Button;
global using Image = System.Windows.Controls.Image;
global using RangeBase = System.Windows.Controls.Primitives.RangeBase;
global using RichTextBox = System.Windows.Controls.RichTextBox;
global using UserControl = System.Windows.Controls.UserControl;
global using Binding = System.Windows.Data.Binding;
global using DataFormats = System.Windows.DataFormats;
global using DataObject = System.Windows.DataObject;
global using DragEventArgs = System.Windows.DragEventArgs;
global using FlowDirection = System.Windows.FlowDirection;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Cursors = System.Windows.Input.Cursors;
global using Brushes = System.Windows.Media.Brushes;
